In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer as imp
from sklearn import preprocessing as prepro
from sklearn.compose import ColumnTransformer as ctf
from sklearn.model_selection import train_test_split as tts

import warnings
warnings.filterwarnings('ignore')

In [2]:
dataset = pd.read_csv('Data1.csv')
dataset
#dataset.isnull()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [3]:
x = dataset.iloc[:,:-1].values

x[4,2] = 0 
x[6,1] = 0
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 0],
       ['France', 35.0, 58000.0],
       ['Spain', 0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [4]:
x_nan =x[:,1:3]
y = dataset.iloc[:,-1].values
x_nan


array([[44.0, 72000.0],
       [27.0, 48000.0],
       [30.0, 54000.0],
       [38.0, 61000.0],
       [40.0, 0],
       [35.0, 58000.0],
       [0, 52000.0],
       [48.0, 79000.0],
       [50.0, 83000.0],
       [37.0, 67000.0]], dtype=object)

In [5]:
#using sklearn to fill the empty space in the dataset
imputer = imp(missing_values = 0, strategy = 'mean')
imputer = imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])
x[:,0]

array(['France', 'Spain', 'Germany', 'Spain', 'Germany', 'France',
       'Spain', 'France', 'Germany', 'France'], dtype=object)

In [6]:
#encoding categorical data eg; sex, country, race, this are data that just shows the category of the rest of data 
x_label_encoder = prepro.LabelEncoder()
x[:,0] = x_label_encoder.fit_transform(x[:,0])
y_label_encoder = prepro.LabelEncoder()
y = y_label_encoder.fit_transform(y)

#using column transformer to transfor the categorized data
transformer = ctf([('one_hot_encoder', prepro.OneHotEncoder(),[0])], remainder='passthrough')

x = np.array(transformer.fit_transform(x), dtype = np.int)

In [7]:
x.view()

array([[    1,     0,     0,    44, 72000],
       [    0,     0,     1,    27, 48000],
       [    0,     1,     0,    30, 54000],
       [    0,     0,     1,    38, 61000],
       [    0,     1,     0,    40, 63777],
       [    1,     0,     0,    35, 58000],
       [    0,     0,     1,    38, 52000],
       [    1,     0,     0,    48, 79000],
       [    0,     1,     0,    50, 83000],
       [    1,     0,     0,    37, 67000]])

In [8]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [9]:
#spliting datasets into trainning and testing
x_train, x_test, y_train, y_test = tts(x,y, test_size = 0.2 ,random_state = 0)


In [10]:
x_train

array([[    0,     1,     0,    40, 63777],
       [    1,     0,     0,    37, 67000],
       [    0,     0,     1,    27, 48000],
       [    0,     0,     1,    38, 52000],
       [    1,     0,     0,    48, 79000],
       [    0,     0,     1,    38, 61000],
       [    1,     0,     0,    44, 72000],
       [    1,     0,     0,    35, 58000]])

In [11]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [12]:
y_test

array([0, 0])

In [13]:
x_test

array([[    0,     1,     0,    30, 54000],
       [    0,     1,     0,    50, 83000]])

In [14]:
ss_x = prepro.StandardScaler()
x_train =ss_x.fit_transform(x_train)
x_test = ss_x.transform(x_test)


In [15]:
x_train

array([[-1.        ,  2.64575131, -0.77459667,  0.27978024,  0.12374357],
       [ 1.        , -0.37796447, -0.77459667, -0.23673712,  0.4617671 ],
       [-1.        , -0.37796447,  1.29099445, -1.95846165, -1.53092514],
       [-1.        , -0.37796447,  1.29099445, -0.06456467, -1.11141099],
       [ 1.        , -0.37796447, -0.77459667,  1.65715986,  1.72030956],
       [-1.        , -0.37796447,  1.29099445, -0.06456467, -0.16750414],
       [ 1.        , -0.37796447, -0.77459667,  0.96847005,  0.98615979],
       [ 1.        , -0.37796447, -0.77459667, -0.58108203, -0.48213975]])

In [16]:
x_test

array([[-1.        ,  2.64575131, -0.77459667, -1.44194429, -0.90165391],
       [-1.        ,  2.64575131, -0.77459667,  2.00150476,  2.13982372]])